const MODULE_TYPES = {
    ENGINE: 1,
    BOOST_ENGINE: 2,
    MINING: 3,
    UTILITY: 4,
    WEAPON_OMNI: 5,
    WEAPON_MISSILE: 6,
    WEAPON_TURRET: 7,
    WEAPON_FIXED: 8,
    AUTOMATION: 9,
    ADVANCED: 10,
    CARGO_CONTAINER: 11
}

export { MODULE_TYPES }
